### ISSUE TITLE
Not defined `program-begin`

### ISSUE THREAD

**Issue by jborden** [dustmop/co2#2]
I just saw this on HN today and I wanted to try it out. However, I am getting this error 

```
$ racket co2.scm -o rom.nes example/example.co2
co2: compile example/example.co2 => .b/example.asm
ERROR @ example/example.co2:29: Not defined `program-begin`
```

I don't see `program-begin` defined anywhere except for in the example files.

Debug info:

```
$ uname -a
Darwin Jupiter 17.7.0 Darwin Kernel Version 17.7.0: Thu Dec 20 21:47:19 PST 2018; root:xnu-4570.71.22~1/RELEASE_X86_64 x86_64
```

;; installed from https://download.racket-lang.org
```
$ racket --version
Welcome to Racket v7.4.
```

**Comment by dustmop** [comment]
Thanks so much for filing this, @jborden. Looks like this is a case of poor test coverage on my part, whoops!

A recent deprecation cleanup removed some directions, but I missed that they were used by many of the example sources. Fixed now.
